# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'resque'
gem 'resque-lock-timeout'
gem 'foreman'
gem 'rake'
gem 'pry'
